version: '3'
services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: pipeline
      POSTGRES_PASSWORD: pipeline-pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_URL: postgresql+psycopg://pipeline:pipeline-pass@db:5432/challenge
      OPENAI_API_KEY: <OPENAI_API_KEY>
      OPENAI_MODEL: gpt-4o
      OPENAI_EMBEDDING_MODEL: text-embedding-3-small
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
